version: '3.7'

services:
  web:
    build: ./Tools/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Tools/:/usr/src/Tools/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ad_tech_tools
      - POSTGRES_PASSWORD=ad_tech_tools
      - POSTGRES_DB=ad_tech_tools_dev

volumes:
  postgres_data:

